Exception in thread Thread-1:
Traceback (most recent call last):
  File "/proj/rmt-PG0/python_install/python3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/proj/rmt-PG0/python_install/python3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cfm/lib/workloads.py", line 65, in __exec
    assert(self.popen.returncode == 0)
AssertionError

container MEMCACHEDV20 already exists, trying to delete
Setting MEMCACHEDV20 memory limit to 9% (1024M) of max
cd /home/cfm/memcachedv2 && echo $$ > /cgroup2/benchmarks/MEMCACHEDV20/cgroup.procs && OMP_NUM_THREADS=1 exec taskset -c 1 /usr/bin/time -v ./memcached


Command terminated by signal 9
        Command being timed: "./memcached"
        User time (seconds): 247.48
        System time (seconds): 1190.92
        Percent of CPU this job got: 56%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 42:03.69
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1051872
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 114616337
        Minor (reclaiming a frame) page faults: 238552900
        Voluntary context switches: 124346875
        Involuntary context switches: 11863
        Swaps: 0
        File system inputs: 152
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0


Python Wall Time: -1669745588.4214342

Major Page Faults,System Time,User Time,Wall Time
114616337,1190.92,247.48,2523.69
